---

- name: Activate powertools
  command: dnf config-manager --set-enabled crb
  when: "'crb' in ansible_local['repolist']['disabled']"

- name: Import EPEL GPG key
  rpm_key:
    key: "{{ epel_gpgkey }}"
    state: present

- name: Install EPEL package
  package:
    name: "{{ epel_package }}"
    state: present
