---

- name: Define proxy to use
  ansible.builtin.set_fact:
    _epel_https_proxy: "{{ epel_https_proxy | default(https_proxy) | default('') }}"
    _epel_http_proxy: "{{ epel_http_proxy | default(http_proxy) | default('') }}"
    _epel_no_proxy: "{{ epel_no_proxy | default(no_proxy) | default('') }}"

- name: Show proxy settings
  ansible.builtin.debug:
    msg:
      https_proxy: "{{ _epel_https_proxy }}"
      http_proxy: "{{ _epel_http_proxy }}"
      no_proxy: "{{ _epel_no_proxy }}"
  when: _epel_https_proxy|length > 0

- name: Download RPM signing key
  ansible.builtin.get_url:
    url: "{{ epel_gpgkey_url }}"
    dest: "{{ epel_gpgkey_file }}"
    validate_certs: "{{ epel_gpg_url_validate_certs | default(True) }}"
    owner: root
    group: root
    mode: "0644"
  register: __rpm_key
  retries: 5
  delay: 15
  until: not __rpm_key.failed
  environment:
    https_proxy: "{{ _epel_https_proxy }}"
    http_proxy: "{{ _epel_http_proxy }}"
    no_proxy: "{{ _epel_no_proxy }}"

- name: Install EPEL from public RPM
  become: yes
  when:
    - epel_mode == 'public'
    - epel_packages is undefined or epel_packages|length == 0
  block:

    - name: Import RPM signing key
      ansible.builtin.rpm_key:
        key: "{{ epel_gpgkey_file }}"
        state: present

    - name: Download RPM package
      ansible.builtin.get_url:
        url: "{{ epel_rpm_package }}"
        dest: "/tmp/{{ epel_rpm_package | basename }}"
        validate_certs: "{{ epel_gpg_url_validate_certs | default(True) }}"
        owner: root
        group: root
        mode: "0644"
      register: __rpm_package
      retries: 5
      delay: 15
      until: not __rpm_package.failed
      environment:
        https_proxy: "{{ epel_https_proxy | default(https_proxy) | default('') }}"
        http_proxy: "{{ epel_http_proxy | default(http_proxy) | default('') }}"
        no_proxy: "{{ epel_no_proxy | default(no_proxy) | default('') }}"

    - name: Install RPM package
      ansible.builtin.dnf:
        name: "/tmp/{{ epel_rpm_package | basename }}"
        state: present

- name: Install EPEL from vendor packages
  become: yes
  when:
    - epel_mode == 'public'
    - epel_packages is defined and epel_packages|length > 0
  block:

    - name: Install RPM package
      ansible.builtin.dnf:
        name: "{{ epel_packages }}"
        state: present

- name: Setup private EPEL repository
  become: yes
  when: epel_mode == 'private'
  block:

    - name: Add EPEL repository (proxy)
      ansible.builtin.yum_repository:
        name: "{{ epel_repo_name }}"
        description: "{{ epel_repo_description }}"
        baseurl: "{{ epel_repo_url }}"
        enabled: "{{ 'yes' if epel_state == 'enabled' else 'no' }}"
        gpgkey: file://{{ epel_gpgkey_file }}
        gpgcheck: yes
