---

- name: Include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/vars/{{ ansible_distribution }}.yml"
    - "{{ role_path }}/vars/family-{{ ansible_os_family }}.yml"
    - "{{ role_path }}/vars/main.yml"

- name: Activate epel
  yum:
    name: "{{ epel_package }}"
    state: present
