---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Setup EPEL
  ansible.builtin.include_tasks: install.yml
  when: epel_state == 'enabled'

- name: Disable EPEL
  ansible.builtin.package:
    name: epel-release
    state: absent
  when: epel_state == 'disabled'
