---

- name: OS check
  fail:
    msg: "This role is only meant for platforms in the Red Hat family"
  when: ansible_os_family != 'RedHat'

- name: Load variables based on OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Setup EPEL
  include_tasks: install.yml
  when: epel_state == 'enabled'

- name: Disable EPEL
  package:
    name: epel-release
    state: absent
  when: epel_state == 'disabled'
