---

- name: Test subscription status
  command: subscription-manager status
  changed_when: no
  failed_when: no
  register: _sat_sub

- block:

    - name: Get list of activated satellite repositories
      command: subscription-manager repos --list-enabled
      check_mode: no
      changed_when: no
      register: sat
      become: yes

    - name: Enable satellite repositories
      command: subscription-manager repos --enable {{ item }}
      become: yes
      loop: "{{ satellite_repositories }}"
      failed_when: no
      when: item not in sat.stdout

  when: _sat_sub.rc == 0

- name: Import EPEL GPG key
  rpm_key:
    key: "{{ epel_gpgkey }}"
    state: present

- name: Install EPEL package
  package:
    name: "{{ epel_package }}"
    state: present
