---

- name: Get list of activated satellite repositories
  command: subscription-manager repos --list-enabled
  check_mode: no
  changed_when: no
  register: sat
  become: tes

- name: Enable satellite repositories
  command: subscription-manager repos --enable {{ item }}
  become: yes
  loop: "{{ sat_repos }}"
  when: item not in sat.stdout

- name: Import EPEL GPG key
  rpm_key:
    key: "{{ epel_gpgkey }}"
    state: present

- name: Install EPEL package
  package:
    name: "{{ epel_package }}"
    state: present
