---

- name: Converge
  hosts: all
  become: "yes"
  roles:
    - deitkrachten.facts
  tasks:
    - name: Include role 'ansible-role-epel'
      ansible.builtin.include_role:
        name: ansible-role-epel
